.TH cbb 1 "Nov 15 1997" "Debian GNU/Linux" ""

.SH NAME
cbb \- Check Book Balancer

.SH SYNOPSYS
.B cbb

.SH DESCRIPTION
.B cbb 
can handle several accounts, balance them, make transfers between
several accounts, give reports and graphs on spending categories.
.PP
.B cbb 
uses perl and the wish Tk interpreter with the X Window System.

.SH AUTHOR
Program developped by Curtis L. Olson <curt@me.umn.edu>
.PP
Manpage written by Philippe Troin <phil@fifi.org> for Debian GNU/Linux.
