.TH dialog4duplicate 1 "October 3 1999" "Debian GNU/Linux" ""

.SH NAME
 \- internal CBB script

.SH DESCRIPTION
.B dialog4duplicate
is an internal script of CBB. Do not invoke by hand.

.SH AUTHOR
Program developped by Curtis L. Olson <curt@me.umn.edu>
.PP
Manpage written by Philippe Troin <phil@fifi.org> for Debian GNU/Linux.
